package com.sweetzpot.stravazpot.activity.model;

public enum ActivityType {
    RIDE,
    RUN,
    SWIM,
    HIKE,
    WALK,
    ALPINE_SKI,
    BACKCOUNTRY_SKI,
    CANOEING,
    CROSSFIT,
    EBIKE_RIDE,
    ELLIPTICAL,
    ICE_SKATE,
    INLINE_SKATE,
    KAYAKING,
    KITE_SURF,
    NORDIC_SKI,
    ROCK_CLIMBING,
    ROLLER_SKI,
    ROWING,
    SNOWBOARD,
    SNOWSHOE,
    STAIR_STEPPER,
    STANDUP_PADDLING,
    SURFING,
    VIRTUAL_RIDE,
    WEIGHT_TRAINING,
    WINDSURF,
    WORKOUT,
    YOGA
}
